V0.4.0 update
SiliconLabs/matter_demo pull request #6
Opened 2022-10-12 17:45 UTC by HusseinElsherbini

Added demos for Boards:
BRD4316A
BRD4317A
BRD4319A
added support for new wifi wstk Swix917 for boards:
BRD4186C
BRD4187C

2022-10-12 18:46 UTC, rerasool approved these changes

2022-10-13 05:25 UTC, mamehta requested changes

2022-10-13 05:25 UTC, mamehta commented on matter_demos.xml
> +		<property key="demos.imageFile" value="Examples/thermostat-app-wifi/siwx917/BRD4186C/chip-efr32-thermostat-example.s37"/>
I see that the path is different for the same app for Wi-Fi for SiWx917 and RS9116. The same binary is used for both. Am I right in understanding that our approach is to copy the same binary to these two different paths?

2022-10-13 05:25 UTC, mamehta commented on matter_demos.xml
> +		<description>This is a Matter Thermostat Application for BRD4186C to be used with SIWX917 Wi-Fi expansion board</description>
Fix the capitalization in the chip name for all 917 examples - SiWx917

2022-10-13 08:23 UTC, mamehta approved these changes

2022-10-13 13:26 UTC, merged